[package]
name = "rocketapp0"
version = "0.1.0"
authors = ["mass10 <mass10.github@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
rocket = "0.4.0"
#rocket_contrib = "*"

[dependencies.rocket_contrib]
version = "0.4.0"
features = ["tera_templates"]
